### PR TITLE
Add go flags to go-to-protobuf

### PR DESCRIPTION
**Pull request by tamalsaha**

### CODE REVIEW

**Comment by tamalsaha** [comment]
@stts, mind taking a look?

**Comment by munnerz** [comment]
This lgtm.

I’ve not had a chance to run it, but does this suffer from error messages with glog along the lines of “ERROR logging before flag.Parse”? I’ve seen this a fair bit with the pflag library and iirc it’s happens once you had the go flags to pflag (although perhaps I recall incorrectly...)

**Comment by munnerz** [comment]
Also this PR should be against `kubernetes/kubernetes` in the staging/ directory

**Comment by tamalsaha** [comment]
Thanks @munnerz . I have reopened the pr herre: https://github.com/kubernetes/kubernetes/pull/54594 . it does not suffer from “ERROR logging before flag.Parse” problem.

**Pull request closed without merging**
